Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  #
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "salt-dev"

  ## For masterless, mount your salt file root
  config.vm.synced_folder "../", "/srv/salt"

  ## Use all the defaults:
  config.vm.provision :shell, inline: 'mkdir -p /srv/pillar'
  config.vm.provision :shell, inline: 'cp /srv/salt/vagrant/top.sls /srv/pillar/top.sls'
  config.vm.provision :shell, inline: 'cp /srv/salt/vagrant/top.sls /srv/salt/top.sls'
  config.vm.provision :shell, inline: '[[ -a /srv/salt/pillar.example ]] || ln -s /srv/salt/pillar.example /srv/pillar/elasticsearch.sls'
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.run_highstate = true
    salt.minion_config = "salt-dev-minion"
    salt.verbose = true
  end
end